### ISSUE TITLE
Error in `tuple.hpp` with Julia 1.10

### ISSUE THREAD

**Issue by eschnett** [JuliaInterop/libcxxwrap-julia#125]
I see this error when using libcxxwrap-julia in Yggdrasil to build for Julia 1.10:
```C++
/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/include/jlcxx/tuple.hpp: In static member function ‘static jl_datatype_t* jlcxx::julia_type_factory<jlcxx::NTuple<N, T> >::julia_type()’:
/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/include/jlcxx/tuple.hpp:137:42: error: cannot convert ‘jl_value_t*’ {aka ‘_jl_value_t*’} to ‘jl_datatype_t*’ {aka ‘_jl_datatype_t*’} in return
     return jl_apply_tuple_type_v(&type, 1);
                                          ^
```

See https://buildkite.com/julialang/yggdrasil/builds/2784#0187e1ef-f3ea-4551-b979-a331dde92109 .

I believe this error was not there a few days ago.

I think BinaryBuilder is using libcxxwrap-julia 0.9.6. Is there a chance this would be corrected in version 0.9.7?

**Comment by giordano** [comment]
This had been fixed by #124
