### ISSUE TITLE
-std=c++14 breaks clang build

### ISSUE THREAD

**Issue by jstrube** [JuliaInterop/libcxxwrap-julia#13]
I'm trying to build against v0.5, but my build is failing on MacOS:
```
[ 50%] Building CXX object CMakeFiles/lciowrap.dir/src/lciowrap.cc.o
/opt/x86_64-linux-gnu/tools/clang++ --sysroot=/opt/x86_64-apple-darwin14/x86_64-apple-darwin14/sys-root  -DJULIA_ENABLE_THREADING -Dlciowrap_EXPORTS -I/workspace/srcdir/LCIOWrapBuilder/include -isystem /workspace/destdir/include -isystem /workspace/destdir/include/julia  -target x86_64-apple-darwin14 --sysroot /opt/x86_64-apple-darwin14/x86_64-apple-darwin14/sys-root -stdlib=libc++ -target x86_64-apple-darwin14 --sysroot /opt/x86_64-apple-darwin14/x86_64-apple-darwin14/sys-root -stdlib=libc++;-std=c++14 -fPIC   -std=c++14 -o CMakeFiles/lciowrap.dir/src/lciowrap.cc.o -c /workspace/srcdir/LCIOWrapBuilder/src/lciowrap.cc
clang-6.0: error: no input files
/bin/sh: -std=c++14: not found
```
I think this is coming from [here](https://github.com/JuliaInterop/libcxxwrap-julia/blob/master/CMakeLists.txt#L116)
Is this really necessary?
Is [this line](https://github.com/JuliaInterop/libcxxwrap-julia/blob/master/CMakeLists.txt#L38) not enough?

**Comment by barche** [comment]
I can't reproduce this with the new test, there is no semicolon in [this line](https://travis-ci.org/JuliaInterop/libcxxwrap-julia/builds/442370182#L4040):

```
/opt/x86_64-linux-gnu/tools/clang++ --sysroot=/opt/x86_64-apple-darwin14/x86_64-apple-darwin14/sys-root  -DJULIA_ENABLE_THREADING -Dtestlib_EXPORTS -isystem /workspace/destdir/include -isystem /workspace/destdir/include/julia  -march=x86-64 -target x86_64-apple-darwin14 --sysroot /opt/x86_64-apple-darwin14/x86_64-apple-darwin14/sys-root -stdlib=libc++ -target x86_64-apple-darwin14 --sysroot /opt/x86_64-apple-darwin14/x86_64-apple-darwin14/sys-root -stdlib=libc++ -O3 -DNDEBUG -fPIC   -std=c++14 -o CMakeFiles/testlib.dir/testlib.cpp.o -c /workspace/srcdir/testlib/testlib.cpp
```

I did have to adapt the build script, setting `CMAKE_FIND_ROOT_PATH`:
https://github.com/JuliaInterop/libcxxwrap-julia/blob/master/testlib-builder/build_tarballs.jl#L10

**Comment by jstrube** [comment]
OK, thanks. I'll try to find out if this is caused by the LCIO dependency. They also use CMAKE; maybe the semicolon sneaks in that way.

**Comment by jstrube** [comment]
Hmm. I have now reproduced that bug with another project, FastJetWrapBuilder.
This line https://travis-ci.com/jstrube/FastJetWrapBuilder/jobs/154017870#L727 also does not contain a semicolon, yet the build still breaks, even on g++. I am a bit puzzled.

**Comment by jstrube** [comment]
Oh, never mind. That one was on gcc 4.8.5. No wonder that option isn't known...

**Comment by jstrube** [comment]
I have no idea how, but this seems to be fixed for me now... Maybe there was some stale code picked up from somewhere in my build. Either way, works now. Thanks for looking into this and sorry for the noise.
