### ISSUE TITLE
Testability of own `libcxxwrap-julia`-based libraries

### ISSUE THREAD

**Issue by sloede** [JuliaInterop/libcxxwrap-julia#141]
While working on a new wrapper for a third-party C++ library, I noticed that there seems to be no obvious way how I can test the newly created `libcxxwrap-julia`-based library. Is using Julia and CxxWrap.jl really the only way to test if everything works as intended or is there another, native (i.e., non-Julia) way to do, e.g., CI testing?

**Comment by barche** [comment]
For QML.jl I do a simple smoke test here: https://github.com/JuliaGraphics/jlqml/blob/main/test/test_module_load.cpp

Actually testing the functionality does require a Julia environment with CxxWrap.jl.

**Comment by sloede** [comment]
OK, thanks for the clarification. I will have a look at the qml repo and how you do testing there 👍
