### ISSUE TITLE
is there plan to support std::optional

### ISSUE THREAD

**Issue by windflowerly** [JuliaInterop/libcxxwrap-julia#149]
is there plan to support std::optional

**Comment by fingolfin** [comment]
This project is mostly driven by volunteers making contributions to scratch their own itch. Meaning: support for `std::optional` or anything else will be added if and when someone volunteers to do it, ideally someone who actually needs it (to ensure the resulting implementation is actually useful in practice).

**Comment by windflowerly** [comment]
if i want to use std::optional, how did i do?

**Comment by windflowerly** [comment]
I got it.please close this issue.
