### ISSUE TITLE
GC rooting with new GC extensions API

### ISSUE THREAD

**Issue by c42f** [JuliaInterop/libcxxwrap-julia#19]
I was just looking at how GC rooting of non-stack objects works here and I saw you've had to resort to a global array at the moment. Luckily the new GC extensions API seems to be just what you need. It's pretty new, is there a plan to integrate it here yet?

Refs:
https://github.com/JuliaLang/julia/pull/28368
https://github.com/JuliaLang/Juleps/blob/master/GcExtensions.md

**Comment by barche** [comment]
Aha, I didn't know about that, looks cool, thanks! I suppose this will be part of Julia 1.1?

**Comment by c42f** [comment]
Yes, it's merged so it'll be part 1.1 which is currently due to enter feature freeze in the middle of the month.

**Comment by barche** [comment]
This is now implemented in the master version of CxxWrap.

**Comment by c42f** [comment]
Oh, very nice!
