### ISSUE TITLE
LICENSE file is missing

### ISSUE THREAD

**Issue by SylvainCorlay** [JuliaInterop/libcxxwrap-julia#2]
This came up as I am working on conda packaging.

**Comment by barche** [comment]
OK, done!

**Comment by SylvainCorlay** [comment]
Thanks! I will add it to the conda package at the next release!

**Comment by SylvainCorlay** [comment]
btw @jakirkham was asking if you were ok to be listed as a recipe maintainer here: https://github.com/conda-forge/staged-recipes/pull/5921

**Comment by SylvainCorlay** [comment]
Thanks!
