### ISSUE TITLE
Global constant set using `set_const` results in null reference

### ISSUE THREAD

**Issue by rgcv** [JuliaInterop/libcxxwrap-julia#23]
So I'm having a bit of an issue setting a constant value for a previously added type. This constant is initialized in a C++ lib I'm trying to (partially) wrap. Namely, I'm trying to wrap some of CGAL's types and functions.

Amazingly, I'm faced with I think is rather unexpected behavior when trying to define the `CGAL::ORIGIN` and `CGAL::NULL_VECTOR` constants. My code looks similar to the following MWE:

```cpp
// cgal.hpp
#include <jlcxx/jlcxx.hpp>
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>

typedef CGAL::Null_vector Null_vector;
typedef CGAL::Origin Origin;

JLCXX_MODULE define_julia_module(jlcxx::Module &module) {
  module.add_type<Origin>();
  module.set_const("ORIGIN", CGAL::ORIGIN);
  // idem for NULL_VECTOR
}

// cgal.cpp
#include "cgal.hpp"
```

```julia
# CGAL.jl
module CGAL
using CxxWrap
@wrapmodule("/path/to/libfile")

export NULL_VECTOR, ORIGIN

function __init__()
  @initcxx
end

end # CGAL

# Sandbox.jl
using CGAL
show(ORIGIN)
```

Running the `Sandbox.jl` file yields the following output:
```
CGAL.OriginRef(Ptr{Nothing} @0x0000000000000000)
```

Now, I may be way off base and `set_const` should only be used alongside bits types (I've also mapped the `CGAL::Orientation` as a bits type and was able to cleanly add three of its values, namely `CGAL::COLLINEAR`, `CGAL::LEFT_TURN`, and `CGAL::RIGHT_TURN` without a hitch). I assume this because I haven't seen any examples of it being used in the fashion I'm using.

I'm guessing this deletion has to do with not being able to be protected against the garbage collector, which leads me to think of either initializing the constant value withing the Julia module instead, or try and make `CGAL::Origin` and `CGAL::Null_vector` bits types and try going that route.. if even possible, apologies for my ignorance, I've been wacking at this for a bit.

Hopefully, it's something I'm doing wrong. If this can't be properly solved, *per se*, I might try the initialization on the Julia side of things instead.

**EDIT**: Can't do the bits workaround, types must be scalars, which they aren't. Maybe through some wrapping magic, creating my own enum.. Seems pointless and sounds like unnecessary extra work since I couldn't just seamlessly wrap around methods/functions that take an instance of `CGAL::Origin` as an argument.

In the meantime, I also tried creating the constant on Julia's side just to see it "disappear" right in front of my eyes, i.e., I get the same behavior as I did before. I'm at a loss at this point :frowning:

**Comment by barche** [comment]
I think this might be related to precompilation, can you test with `__precompile__(false)` at the top of your module? The way I understand, the constant is compiled in, and this sets the pointer to null when the module is loaded.

**Comment by rgcv** [comment]
I'll be darned, that did it! Here's a screen of a small usage (inside Atom):

![image](https://user-images.githubusercontent.com/4052080/55196786-5db4db00-51a8-11e9-81e7-b86a9752382e.png)

Though, this worries me. By preventing precompilation, would the module have to be compiled *every time* it's behind loaded? Won't that hinder performance in the process?

**Comment by barche** [comment]
Yes, turning off precompilation should only be done for debugging. The simplest workaround for this would be to wrap a function that returns the constant. As a next step, you could experiment with a global const `Ref` to the value, which you initialize in the module `__init__` function.

**Comment by rgcv** [comment]
Sounds hacky, but fair. Glad to report the workaround works wonderfully. Lambda's probably being replaced for a regular function definition to avoid unnecessary overhead, but for the sake of the example:

```cpp
// cgal.hpp
#include <jlcxx/jlcxx.hpp>
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>

typedef CGAL::Null_vector Null_vector;
typedef CGAL::Origin Origin;

JLCXX_MODULE define_julia_module(jlcxx::Module &module) {
  module.add_type<Origin>("Origin");
  module.method("__origin", []() -> const Origin& { return CGAL::ORIGIN; }
  // idem for NULL_VECTOR
}

// cgal.cpp
#include "cgal.hpp"
```

```julia
# CGAL.jl
module CGAL
using CxxWrap
@wrapmodule("/path/to/libfile")

function __init__()
  @initcxx
  global ORIGIN = __origin()
  # idem for NULL_VECTOR
end

end # CGAL

# Sandbox.jl
using CGAL
@show ORIGIN
```
yields
```
ORIGIN = CGAL.OriginRef{Ptr{Nothing} @0x00007f9f3ea26ed3)
CGAL.OriginRef{Ptr{Nothing} @0x00007f9f3ea26ed3)
```

**Comment by rgcv** [comment]
Sorry, goffing around with shortcuts, reopening (though briefly, I imagine).

**Comment by barche** [comment]
OK, so the reason to use a const `Ref` would be mostly for performance, since a non-const global is slow to access in Julia.

I have looked a bit at the implementation of Origin, and it looks like it is just an empty class. This means that you could directly map it to an empty Julia struct declared on the Julia side and define `const ORIGIN = Origin()`

`ImmutableBits` in the types example is the relevant example for this:

https://github.com/JuliaInterop/CxxWrap.jl/blob/master/test/types.jl#L8
https://github.com/JuliaInterop/libcxxwrap-julia/blob/master/examples/types.cpp (look for all occurences of ImmutableBits, you need to specialize some jlcxx templates)

Note that I am simplifying this system a lot in response to issue #134.

**Comment by rgcv** [comment]
That makes sense, I'm guessing it would be related with the ability of caching its value..

I managed to hack a very quick mirroring of the `ImmutableBits` example, and everything seems fine, the mapping is established correctly. Alas, when I attempt to involve q method that accepts the constant, the underlying `ccall` fails, complaining the 2nd argument isn't a C type.

So it seems that I'm currently at another dead end.. I'll keep looking and see if I missed something. I might edit this comment and add the code later, can't do it atm.

**Comment by barche** [comment]
This should no longer be a problem in CxxWrap 0.9 and later.
