### ISSUE TITLE
Consider supporting C++14

### ISSUE THREAD

**Issue by SylvainCorlay** [JuliaInterop/libcxxwrap-julia#32]
**Would you consider supporting C++14 instead of requiring C++17?***

It seems that CxxWrap / libcxxwrap-julia is using a few features from C++17 standard (`constexpr if`, `std::bool_constant`, fold expressions).

In PR https://github.com/xtensor-stack/xtensor-julia/pull/23, I am working on updating Xtensor.jl to support the latest version of libcxxwrap-julia and it forces us to drop support for GCC 5 and GCC 6...

FYI, we have some polyfill for e.g. `constexpr if` in xtl that we use across the codebase of xtensor and related projects...

**Comment by SylvainCorlay** [comment]
Note: we are happy to help polyfill the `if constexpr` with the things we have been doing in xtensor...

**Comment by SylvainCorlay** [comment]
cc @barche would you consider making libcxxwrap compatible with C++14?

**Comment by barche** [comment]
I would prefer not to, since the code is simpler in C++17. Is it really such a big problem to drop gcc6 and earlier?

**Comment by SylvainCorlay** [comment]
> I would prefer not to, since the code is simpler in C++17. Is it really such a big problem to drop gcc6 and earlier?

If we can avoid it, it is good. :) If you are interested, I can make a PR using a `static_if` polyfill for you to review.

@mingwandroid was also mentioning that C++17 had some consequences wrt to ABI compatibility so it may be preferable for e.g. conda-forge to not need the C++17 flag, even though conda-forge builds with GCC7.

**Comment by barche** [comment]
I wouldn't oppose a PR, but I'm not sure it's worth the extra work? It seems that even boost will require C++17, unless I'm misinterpreting this: https://github.com/conda-forge/boost-feedstock/issues/75

?

**Comment by SylvainCorlay** [comment]
If the concerns about c++ abi with respect to enabling c++17 are founded, this should probably not go through.

**Comment by barche** [comment]
OK, so maybe it's best to hang on a bit and see how it plays out with Boost?

**Comment by SylvainCorlay** [comment]
Well, there is still the question of having to drop every GCC<7...

**Comment by SylvainCorlay** [comment]
@barche there seems to be another issue with C++17.

 - MSVC 2015 and MSVC 2017 don't support fold expressions
 - the version of mingw packaged with conda-forge does not appear to support all the C++17 features that we use.

In xtensor-julia, we also had to drop all gcc<7 versions, as well as xcode8 and xcode9 that were previously supported.

**Comment by barche** [comment]
OK, maybe we can find a compromise: I could accept a PR for C++14 compatibility for the libcxxwrap v0.6 branch, which will remain in sync with the CxxWrap.jl v0.9 branch ( see https://github.com/JuliaInterop/CxxWrap.jl/issues/202 )

**Comment by SylvainCorlay** [comment]
>  I could accept a PR for C++14 compatibility for the libcxxwrap v0.6 branch,

Great! we have polyfills for the C++17 features that you use, which we have been using in xtensor and friends, so I am confident that it will work.
