### ISSUE TITLE
BinaryBuilder v0.2 support

### ISSUE THREAD

**Issue by jstrube** [JuliaInterop/libcxxwrap-julia#37]
Please consider updating the build script to supporting BinaryBuilder v0.2 before releasing CxxWrap 0.9.

**Comment by jstrube** [comment]
I'm trying to update the julia build recipe in Yggdrasil...
https://github.com/JuliaPackaging/Yggdrasil/pull/314

**Comment by barche** [comment]
For the 0.9 release the binaries will be built using Yggdrasil, given the roadblock on your PR above probably by using the existing Julia binaries.

**Comment by jstrube** [comment]
Well, there's https://github.com/Gnimuc/JuliaBuilder/releases, which has at least binaries for 1.3, but I don't know if that makes a difference.
