### ISSUE TITLE
Provide as BB artifact

### ISSUE THREAD

**Issue by ViralBShah** [JuliaInterop/libcxxwrap-julia#51]
For packages that depend on this library, we need to have it as a BB artifact.

**Comment by barche** [comment]
Yep, this is planned for the next release. The JLL already exists, but I wasn't yet using it "properly" to keep compatibility with Julia < 1.3.

**Comment by ViralBShah** [comment]
What is the current jll called?

**Comment by barche** [comment]
It's at https://github.com/JuliaBinaryWrappers/libcxxwrap_julia_jll.jl ( created from Yggdrasil https://github.com/JuliaPackaging/Yggdrasil/tree/master/C/cxxwrap_julia )

**Comment by ViralBShah** [comment]
Thanks. I don't know what I did since I didn't find it, bit it is the obvious name!

**Comment by jstrube** [comment]
Sorry for hijacking the thread, but I'm trying to build against the new jll, unsuccessfully.
I'm getting this:
https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=2893&view=logs&j=cc825568-a615-5434-54d1-66f9aad1b79c&t=40721762-5a4f-51a4-8a9a-d8255070857f&l=4722
```
CMake Error in CMakeLists.txt:
[00:51:22]   Imported target "JlCxx::cxxwrap_julia" includes non-existent path
[00:51:22] 
[00:51:22]     "/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/include"
[00:51:22] 
[00:51:22]   in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
[00:51:22] 
[00:51:22]   * The path was deleted, renamed, or moved to another location.
[00:51:22] 
[00:51:22]   * An install or uninstall procedure did not complete successfully.
[00:51:22] 
[00:51:22]   * The installation package was faulty and references files it does not
[00:51:22]   provide.
```
I had previously downloaded the tarball and copied the include files manually, but obviously that defeats the purpose of the jlls...

**Comment by jstrube** [comment]
although, looking at this more closely, this is a CMake error. It's quite possible that I didn't use the right incantation of CMake. Please advise.

**Comment by ViralBShah** [comment]
cc @giordano

**Comment by barche** [comment]
> Thanks. I don't know what I did since I didn't find it, but it is the obvious name!

Well, apparently the builder was in the wrong directory, it is now in https://github.com/JuliaPackaging/Yggdrasil/tree/master/L/libcxxwrap_julia ;)

**Comment by giordano** [comment]
Where is the `/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/include` path coming from?  What's it for?  I'm not convinced by the "local" bit

**Comment by jstrube** [comment]
This was fixed by adding `-DCMAKE_FIND_ROOT_PATH="$prefix"` as recommended by a comment in the PR.

**Comment by jstrube** [comment]
@ViralBShah note that on your list libcxxwrap-julia is listed next to Cxx. It should be next to CxxWrap.

**Comment by ViralBShah** [comment]
I knew that - but seems like I edited it in the wrong place.

**Comment by barche** [comment]
> This was fixed by adding `-DCMAKE_FIND_ROOT_PATH="$prefix"` as recommended by a comment in the PR.

Glad it's fixed, but I have no idea why this wasn't needed before? Maybe it's something to put into the toolchain file, @giordano ?

**Comment by jstrube** [comment]
It's strange. I notice that I still have an `ln -s` of the include path to `usr/bin/local` in my build script. This had been put in before to work around this. Let me remove and see if it still works...

**Comment by jstrube** [comment]
Ok, looks like the `ln -s` workaround is no longer needed with this new flag.

**Comment by giordano** [comment]
> Maybe it's something to put into the toolchain file, @giordano ?

Yes, this might be a good idea.  Need to update the cmake toolchain files in https://github.com/JuliaPackaging/Yggdrasil/tree/master/0_RootFS/PlatformSupport/bundled/buildsystem_toolchains

**Comment by barche** [comment]
CxxWrap 0.10 is out now and no longer depends on BinaryProvider, using the JLL directly instead, so I think this can be closed. I opened a separate issue for the `CMAKE_FIND_ROOT_PATH` option in Yggdrasil.
