### ISSUE TITLE
Pedantic compiler warning

### ISSUE THREAD

**Issue by phinzphinz** [JuliaInterop/libcxxwrap-julia#67]
[This line](https://github.com/JuliaInterop/libcxxwrap-julia/blob/771c84439aa9060136c5a99f81114c7e0a0453ef/include/jlcxx/type_conversion.hpp#L658) causes the following warning:

`libcxxwrap-julia/include/jlcxx/type_conversion.hpp:658:2: warning: extra ‘;’ [-Wpedantic]`

**Comment by barche** [comment]
Thanks, should be fixed on master!
